apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Just a demo
  labels:
    application: myapp-demo
    size: small
    team: team-a
    environment: dev
  name: myapp-demo-