apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Demo 1
  labels:
    application: new-app-onboard
    size: small
    team: admin
    environment: dev
  name: new-app-onboard-